export const REMOVE_ITEM_CART = "REMOVE_ITEM_CART";
export const CLEAR_ITEM_CART = " CLEAR_ITEM_CART";
export const INCREMENT_ITEM_CART = "INCREMENT_ITEM_CART";
export const DECREMENT_ITEM_CART = "DECREMENT_ITEM_CART";

export const GET_TOTAL_CART = "GET_TOTAL_CART";

export const ADD_TO_CART="ADD_TO_CART"