export const singleProductName = [
  "All Sarees",
  "Silk Sarees",
  "Cotton Silk Sarees",
  "Cotton Sarees",
  "Georgette Sarees",
  "Chiffon Sarees",
  "Satin Sarees",
  "Embroidered Sarees",
  "All Kurtis",
  "Anarkali",
  "Kurties",
  "Rayon",
  "Kurties",
  "Cotton",
  "Kurties",
  "Embroidered",
  "Kurtis",
  "All Suits & Dress Material",
  "Cotton",
  "Embroidered Suits",
  "Chanderi Suits",
  "Jeans",
  "Jegging",
  "Palazzos",
  "Shorts",
  "Skirts",
  "Bra",
  "Brief",
  "Nightsuits",
  "Babydolls",
  "All Top Wear",
  "Tshirts",
  "Shirts",
  "Track Pants",
  "Skirts",
  "Track Pants",
  "Jeans",
  "Trousers",
  "All Men Accessories",
  "Watches",
  "Belts",
  "Wallet",
  "Jewellery",
  "Sunglasses",
  "Bags",
  "Casual Shoe",
  "Sports Shoe",
  "Sandals",
  "Formal Shoes",
  "Men Kurtas",
  "Ethnic Jackets",
  "All Inner & Sleep",
  "Vests",
  "Dresses",
  "Rompers",
  "Soft Toys",
  "Footwear",
  "Stationery",
  "Wtaches",
  "Bags & Backpacks",
  "All Baby Care",
  "BedSheets",
  "Doormats",
  "Curtains & Sheers",
  "Cushion & Cusion Covers",
  "Mattress Protectors",
  "All Application",
  "Grooming",
  "Home Appliances",
  "All Mobile & Accessories",
  "Smartwatches",
  "Mobile Holders",
  "Mobile cases and covers",
  "Flats",
  "Bellies",
  "Juttis",
  "Sports Shoes",
  "Casual Shoes",
  "Formal Shoes",
  "Sandals",
  "All Men Bags",
  "Men Wallets",
  "All Women Bags",
  "Handbags",
  "Clutches",
  "Slingbags",
  "Bags",
  "Watches",
  "Hair Accessories",
  "Sunglasses",
  "Deodorants",
  "Jewellery Set",
  "Earrings",
  "Mangalsutras",
  "Studs",
  "Bangles",
  "Necklaces",
  "Rings",
  "Anklets",
  "Deodorants",
  "Sanitizers",
  "Oral Care",
  "Feminine Hygiene",
  "Face",
  "Eyes",
  "Lips",
  "Nails",
  "Kitchen Storage",
  "Cookware & Bakeware",
  "All Home Decor",
  "Stickers",
  "Clocks",
  "Showpieces",
];
